/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoIdRouteImport } from './routes/acesso.$id'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoIdRoute = AcessoIdRouteImport.update({
  id: '/acesso/$id',
  path: '/acesso/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso/$id': typeof AcessoIdRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso/$id': typeof AcessoIdRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso/$id': typeof AcessoIdRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso/$id'
    | '/api/public/geo'
    | '/api/public/track'
    | '/api/public/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso/$id'
    | '/api/public/geo'
    | '/api/public/track'
    | '/api/public/upload'
  id:
    | '__root__'
    | '/'
    | '/acesso/$id'
    | '/api/public/geo'
    | '/api/public/track'
    | '/api/public/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoIdRoute: typeof AcessoIdRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso/$id': {
      id: '/acesso/$id'
      path: '/acesso/$id'
      fullPath: '/acesso/$id'
      preLoaderRoute: typeof AcessoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoIdRoute: AcessoIdRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
