plugins {
    id "com.android.application"
}

android {
    namespace "br.com.mcr.rendimento"
    compileSdk 36

    defaultConfig {
        applicationId "br.com.mcr.rendimento"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "1.2.0"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "androidx.core:core:1.17.0"
    implementation "androidx.webkit:webkit:1.14.0"
}
